version: '3.8'
services:
  fe-app:
    image: fe-container:first
    # build:
      # context: ./www/meeting_room_booking_system_frontend_admin
      # dockerfile: ./www/meeting_room_booking_system_frontend_admin/Dockerfile
    ports:
      - 81:80
    depends_on:
      - nest-app
    networks:
      - common-network
    restart: always
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
      - minio-container
    ports:
      - 3005:3005
    networks:
      - common-network
    restart: always
  mysql-container:
    image: mysql
    volumes:
      - D:\Docker tmp\mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    networks:
      - common-network
    restart: always
  redis-container:
    image: redis
    volumes:
      - D:\Docker tmp\redis:/data
    ports:
      - 4344:6379
    networks:
      - common-network
    restart: always
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - D:\Docker tmp\minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456
    networks:
      - common-network
    restart: always
networks:
  common-network:
    driver: bridge
